import Head from "next/head";
import {Container, Typography, Box} from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fullstack Interview – Alveno</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Container maxWidth="md">
        <Box my={4}>
          <Typography variant="h4" component="h1" gutterBottom>
            Zadání fullstack úkolu
          </Typography>
          <Typography variant="h6" component="h2" gutterBottom>
            Cíl:
          </Typography>
          <Typography variant="body1" gutterBottom>
            Vašim úkolem je vytvořit v předchystané mini aplikaci stránku, která zobrazí seznam týmů a jejich
            zaměstnanců. Tento úkol bude vyžadovat úpravy na backendu i na frontendu.
          </Typography>
          <Typography variant="h6" component="h2" gutterBottom mt={2}>
            Úkoly:
          </Typography>
          <ul>
            <li>Prozkoumejte backendovou i frontendovou část aplikace.</li>
            <li>Načtěte a zobrazte data na frontendu.</li>
            <ul>
              <li>
                Zachovejte hierarchickou (vnořenou) strukturu týmů a jejich zaměstnanců.
              </li>
              <li>Umožněte zobrazování a skrývání obsahu týmů.</li>
              <li>
                U zaměstnanců vykreslete i další údaje, zaměstnance, co již nepracují (mají endDate v minulosti)
                zobrazte odlišně.
              </li>
            </ul>
            <li>Umožněte zprávu týmů a zaměstnanců.</li>
            <ul>
              <li>
                Můžete použít předpřipravené formuláře TeamAdd.tsx a EmployeeAdd.tsx.
              </li>
              <li>
                Implementujte také hromadné mazání zaměstnanců na základě výběru jednoho
                či více zaměstnanců.
              </li>
            </ul>
          </ul>
          <Typography variant="h6" component="h2" gutterBottom>
            Způsob práce:
          </Typography>
          <ul>
            <li>
              Cílem těchto cvičení je odpovědět na následující otázky:
            </li>
            <ul>
              <li>Jaké technologie (knihovny) jsou v aplikaci použity?</li>
              <li>Jaké změny je potřeba provést v obou částech aplikace, aby správně fungovala?</li>
              <li>Vidíte v aplikaci nějaká místa, které by šlo zlepšit, prípadně něco problematického nebo nebezpečného?</li>
            </ul>
          </ul>
          <Typography variant="h6" component="h2" gutterBottom>
            Časová náročnost:
          </Typography>
          <Typography variant="body1" gutterBottom>
            Odhadovaná náročnost úkolu (psaní kódu není nutnost) je do 1 MD.
          </Typography>
          <Typography variant="h6" component="h2" gutterBottom  mt={2}>
            Kontakt:
          </Typography>
          <Typography variant="body1" gutterBottom>
            V případě nejasností se obraťte na{" "}
            <a href="mailto:bem@alveno.cz">bem@alveno.cz</a>
          </Typography>
        </Box>
      </Container>
    </>
  );
}
